// config.h is generated by cmake while build freetype-gl from template config.h.in by cmake variable status

#define FREETYPE_GL_USE_GLEW @FREETYPE_GL_USE_GLEW@
#define FREETYPE_GL_USE_VAO @FREETYPE_GL_USE_VAO@
#define GL_WITH_GLAD @GL_WITH_GLAD@
